#서버 설정
server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      charset: UTF-8

# view resolver 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/board/
      suffix: .jsp
     
      
# DataSource 설정
  datasource:
    username: scott
    url: jdbc:oracle:thin:@localhost:1521:xe
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver
   